variables:
    STACK_NAME:
        default: elasticsearch-stack
        description: ElasticSearch Cloudformation stack name
        overrides: null
        required: true
        type: string
    ES_DOMAIN_NAME:
        default: "coreoes"
        required: false
        description: A name for the Amazon ES domain.
        type: string
    ES_VERSION:
        default: "5.1"
        required: false
        description: The version of Elasticsearch to use, such as 5.1.
        type: string
    ES_DEDICATED_MASTER_COUNT:
        required: false
        description: Dedicated master instance count.
        type: number
        default: 2
    ES_DEDICATED_MASTER_TYPE:
        default: "m3.medium.elasticsearch"
        required: false
        type: string
        description: Dedicated master instance type. The hardware configuration of the computer that hosts the dedicated master node, such as m3.medium.elasticsearch. 
    ES_INSTANCE_COUNT:
        default: 4
        required: false
        description: The number of data nodes (instances) to use in the Amazon ES domain.
        type: number
    ES_INSTANCE_TYPE:
        default: "m4.large.elasticsearch"
        required: false
        description: The instance type for your data nodes, such as m3.medium.elasticsearch.
        type: string
    ES_EBS_VOLUME_SIZE:
        default: 100
        required: false
        description: The size of the EBS volume for each data node.
        type: number
    ES_EBS_VOLUME_IOPS:
        default: 0
        required: false
        description: The number of I/O operations per second (IOPS) that the volume supports.
        type: number
    ES_SNAPSHOT_START_HOUR:
        default: 0
        required: false
        description: Snapshot start hour.
        type: number
    CFN_DISABLE_ROLLBACK:
        description: Set to true to disable rollback of the stack if stack creation failed.
        required: false
        type: string
    CFN_ON_FAILURE:
        default: ROLLBACK
        description: "Action to be taken if stack creation fails. This must be one of: DO_NOTHING, ROLLBACK, or DELETE. Conflicts with disable_rollback."
        required: false
        type: string
    CFN_TIMEOUT_IN_MINUTES:
        default: 60
        description: The amount of time that can pass before the stack status becomes CREATE_FAILED.
        required: false
        type: number
    CFN_CAPABILTIES:
        default:
            - CAPABILITY_IAM
        description: A list of capabilities.
        required: false
        type: array
    CFN_NOTIFICATION_ARNS:
        description: The Simple Notification Service (SNS) topic ARNs to publish stack related events.
        required: false
        type: array
    CFN_POLICY_URL:
        description: Location of a file containing the stack policy. Conflicts w/ POLICY_BODY.
        required: false
        type: string
    CFN_POLICY_BODY:
        description: Structure containing the stack policy body. Conflicts w/ POLICY_URL.
        required: false
        type: string
    CFN_ROLE_ARN:
        description: The Amazon Resource Name (ARN) of an AWS Identity and Access Management (IAM) role that AWS CloudFormation assumes to update the stack.
        required: false
        type: string
    CFN_TAGS:
        required: false
        description: tags to apply to the cloudformation stack
        type: array
        default: